Initial
digitalbazaar/web-app-manifest-utils pull request #2
Opened 2020-11-11 17:16 UTC by JoshDunnDev

2020-11-11 17:29 UTC, dlongley requested changes

2020-11-11 17:29 UTC, dlongley commented on WebAppManifestClient.js
> +    // TODO: use different httpsAgent?
Nope, use the same one.

2020-11-11 17:29 UTC, dlongley commented on WebAppManifestClient.js
> +  async getManifest({origin}) {
Can we have separate functions that get the manifest from the origin directly and that get it from the proxy as well -- so we can call those if desired? Then this function can call those helpers internally.

2020-11-18 19:49 UTC, dlongley requested changes
Looks like I never clicked submit on this review... submitting now.

2020-11-18 19:49 UTC, dlongley commented on WebAppManifestClient.js
> +  async getManifest({origin}) {
Here and on all public methods:

```suggestion
  async getManifest({origin} = {}) {
```

2020-11-18 19:49 UTC, dlongley commented on WebAppManifestClient.js
> +    const {defaultHeaders: headers, agent} = this;
```suggestion
    if(!(origin && typeof origin === 'string')) {
      throw new TypeError('"origin" must be a non-empty string.');
    }
    const {defaultHeaders: headers, agent} = this;
```

2020-11-18 19:49 UTC, dlongley commented on WebAppManifestClient.js
> +      return {manifest, icon};
So, we shouldn't fetch the favicon, as that will require CORS to be used there as well. Rather, if a `defaultIcon` is given, we use that, if not, we use `icon.src = <faviconUrl>`. So the caller of the API will decide if they want a default icon or if they want it to default to using a favicon -- which will have to be detected as present later. Fetching a favicon in a Web UI happens via an `img` tag, which avoids CORs, so the model is a bit different from fetching the manifest.json file.

2020-12-01 19:17 UTC, JoshDunnDev commented on WebAppManifestClient.js
> +      return {manifest, icon};
So what if a favicon does not exist? Are you saying this would be detected at a different level than this?

2020-12-01 19:26 UTC, dlongley commented on WebAppManifestClient.js
> +      return {manifest, icon};
@JoshDunnDev, yes, a component that uses an `img` tag to show a favicon should have a fallback for a 404 case.  So -- this is handled at a higher level.

2021-12-15 19:58 UTC, dlongley commented
@JoshDunnDev -- What's the status here? It looks like a review was never re-requested. Did this work get finished and is it ready for review?

2021-12-15 20:00 UTC, dlongley requested changes

2021-12-15 20:00 UTC, dlongley commented on WebAppManifestClient.js
>        return {manifest, icon};
This is simpler, right?

```suggestion
      icon.src = defaultIcon || `${origin}/favicon.ico`;
      return {manifest, icon};
```

2021-12-15 20:00 UTC, dlongley commented on WebAppManifestClient.js
> +        `${origin}/favicon.ico`;
```suggestion
      icon.src = defaultIcon || `${origin}/favicon.ico`;
```

2022-01-13 03:13 UTC, merged